// Generated by CoffeeScript 1.3.1
(function() {

  Ext.define('ManagedMissions.view.MissionTripMemberDetailsContainer', {
    extend: 'Ext.Container',
    id: 'missionTripMemberDetailsContainer',
    config: {
      listeners: {
        updatedata: function(component, data, eOpts) {
          return this.config.title = "" + data.FirstName + " " + data.LastName;
        }
      },
      tpl: '<p>Email: <tpl if="EmailAddress"><a href="mailto:{EmailAddress}">{EmailAddress}</a></tpl></p><p>Phone Number: <tpl if="PhoneNumber">{PhoneNumber}</tpl></p>'
    }
  });

}).call(this);
