// Generated by CoffeeScript 1.3.1
(function() {

  Ext.define('ManagedMissions.controller.Login', {
    extend: 'Ext.app.Controller',
    requires: ['Ext.data.JsonP', 'Ext.MessageBox'],
    config: {
      routes: {
        'login': 'new'
      },
      refs: {
        mainContainer: '#mainContainer',
        loginFormPanel: '#loginFormPanel',
        loginButton: '#loginButton'
      },
      control: {
        loginButton: {
          tap: 'onLoginButtonTap'
        }
      }
    },
    "new": function() {
      var loginFormPanel;
      loginFormPanel = this.getLoginFormPanel() || Ext.create('ManagedMissions.view.LoginFormPanel');
      return Ext.Viewport.setActiveItem(loginFormPanel);
    },
    onLoginButtonTap: function(button, event, options) {
      var data;
      data = this.getLoginFormPanel().getValues();
      return Ext.data.JsonP.request({
        url: 'https://managedmissions-proxy.herokuapp.com/api/auth/logon',
        params: data,
        scope: this,
        success: function(data) {
          if (data.success) {
            return this.redirectTo('mission_trips');
          } else {
            return Ext.Msg.alert('Authentication Error', 'We were unable to log you in. Please check your email and password or try again in a few minutes.', Ext.emptyFn);
          }
        },
        failure: function(errorType) {
          return Ext.Msg.alert('Authentication Error', 'We were unable to log you in. Please check your network connection or try again in a few minutes.', Ext.emptyFn);
        }
      });
    }
  });

}).call(this);
