// Generated by CoffeeScript 1.3.1
(function() {

  Ext.define('ManagedMissions.controller.Members', {
    extend: 'Ext.app.Controller',
    config: {
      refs: {
        missionTripsNavigationView: '#missionTripsNavigationView',
        missionTripTabPanel: '#missionTripTabPanel',
        missionTripMembersList: '#missionTripMembersList',
        missionTripMemberDetailsContainer: '#missionTripMemberDetailsContainer'
      },
      control: {
        missionTripTabPanel: {
          updatedata: 'onMissionTripTabPanelUpdateData'
        },
        missionTripMembersList: {
          disclose: 'onMissionTripMembersListDisclose'
        }
      }
    },
    onMissionTripTabPanelUpdateData: function(component, data, eOpts) {
      var proxy, store;
      store = Ext.getStore('Members');
      proxy = store.getProxy();
      if (proxy.config.extraParams.missionTripId !== data.MissionTripId) {
        proxy.config.extraParams.missionTripId = data.MissionTripId;
        return store.load();
      }
    },
    onMissionTripMembersListDisclose: function(list, record, target, index, e, eOpts) {
      var missionTripMemberDetailsContainer, missionTripsNavigationView;
      missionTripsNavigationView = this.getMissionTripsNavigationView();
      missionTripMemberDetailsContainer = this.getMissionTripMemberDetailsContainer() || Ext.create('ManagedMissions.view.MissionTripMemberDetailsContainer');
      missionTripMemberDetailsContainer.setRecord(record);
      return missionTripsNavigationView.push(missionTripMemberDetailsContainer);
    }
  });

}).call(this);
